// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Image from './Image';
import Matches from './Matches';
import OngoingTournaments from './OngoingTournaments';
import OurTeam from './OurTeam';
import Partners from './Partners';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';
import WeAre from './WeAre';

export {
  Hero,
  Image,
  Matches,
  OngoingTournaments,
  OurTeam,
  Partners,
  TextWithFeatures,
  TextWithImage,
  WeAre,
};

export const components = {
  hero: Hero,
  image: Image,
  matches: Matches,
  ongoing_tournaments: OngoingTournaments,
  our_team: OurTeam,
  partners: Partners,
  text_with_features: TextWithFeatures,
  text_with_image: TextWithImage,
  we_are: WeAre,
};
