// Code generated by Slice Machine. DO NOT EDIT.

import HeadTournaments from './HeadTournaments';
import Hero from './Hero';
import Image from './Image';
import MainSlider from './MainSlider';
import Matches from './Matches';
import OngoingTournaments from './OngoingTournaments';
import OurTeam from './OurTeam';
import Page404 from './Page404';
import PartnerForm from './PartnerForm';
import Partners from './Partners';
import PartnersList from './PartnersList';
import PlaterMain from './PlaterMain';
import PlayerGear from './PlayerGear';
import ShowMatchesBlock from './ShowMatchesBlock';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';
import WeAre from './WeAre';

export {
	HeadTournaments,
	Hero,
	Image,
	MainSlider,
	Matches,
	OngoingTournaments,
	OurTeam,
	Page404,
	PartnerForm,
	Partners,
	PartnersList,
	PlaterMain,
	PlayerGear,
	ShowMatchesBlock,
	TextWithFeatures,
	TextWithImage,
	WeAre,
};

export const components = {
	head_tournaments: HeadTournaments,
	hero: Hero,
	image: Image,
	main_slider: MainSlider,
	matches: Matches,
	ongoing_tournaments: OngoingTournaments,
	our_team: OurTeam,
	page404: Page404,
	partner_form: PartnerForm,
	partners: Partners,
	partners_list: PartnersList,
	plater_main: PlaterMain,
	player_gear: PlayerGear,
	show_matches_block: ShowMatchesBlock,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
	we_are: WeAre,
};
